# NOTE: be sure to bump the version in chrome/manifest.json before running this

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Zip extension
        run: (cd chrome; zip -r -FS ../chrome.zip *)

      - name: Deploy to Chrome Store
        uses: mnao305/chrome-extension-upload@1.1.1
        with:
          file-path: ./chrome.zip
          extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
