# NOTE: be sure to bump the version in chrome/manifest.json before running this

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Zip extension
        run: (cd chrome; zip -r -FS ../chrome.zip *)
        
      - name: Deploy to FireFox Developer Hub
        uses: trmcnvn/firefox-addon@v1
        with:
          uuid: ${{ secrets.FIREFOX_UUID }}
          xpi: ./chrome.zip
          manifest: ./chrome/manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
