on:
  push:
    branches:
      - main
    paths:
     - 'server/**'

defaults:
  run:
    working-directory: server

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy environment variables
        run: cp .env.dev .env

      - name: Build image
        run: docker build -t jmensch1/codeflower:${{github.sha}} .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: jmensch1
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker push jmensch1/codeflower:${{github.sha}}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_PRIVATE_KEY }}
          script: |
            docker pull jmensch1/codeflower:${{github.sha}}
            docker stop codeflower
            docker rm codeflower
            docker run -d \
              --restart always \
              -p 80:8000 \
              --name codeflower \
              -e SENDGRID_EMAIL='jake.mensch@gmail.com' \
              jmensch1/codeflower:${{github.sha}}
